name: NoMinimapSorry
main: dev.dejay.nominimapsorry.NoMinimapSorry
version: '${version}'
description: Disables Xaero's Maps
authors:
  - DeJayDev
api-version: '1.20'
depend: [ProtocolLib, packetevents]
